//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskAssign
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
